#!/usr/bin/env bash
#: Title:       sk-nft-apply
#: Synopsis:    sk-nft-apply [--profile web-server|ssh-only] [--file FILE] [--dry-run] [--persist] [--yes]
#:              [--ssh-port N]
#: Description: Apply a raw nftables ruleset on Debian/Ubuntu or the RHEL family.
#:              Either generates a safe default-deny inet/filter ruleset from a
#:              built-in profile, or loads a user-supplied .nft file. ALWAYS
#:              syntax-checks (nft -c) first. In --dry-run it prints/checks the
#:              ruleset and stops. A real apply is a DESTRUCTIVE operation
#:              (replaces the live ruleset) and requires confirmation. Refuses to
#:              run while ufw/firewalld is active (they own the ruleset) unless
#:              --force. Optionally persists via nftables.service. See
#:              references/nftables-and-iptables.md.
#: Author:      Peter Bamuhigire <techguypeter.com>
#: Contact:     +256784464178
#: Version:     0.1.0

# =============================================================================
# 1. Library + safety
# =============================================================================
set -uo pipefail

SK_LIB="/usr/local/lib/linux-skills/common.sh"
if [[ ! -f "$SK_LIB" ]]; then
    _SD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    SK_LIB="${_SD}/lib/common.sh"
fi
# shellcheck source=/dev/null
source "$SK_LIB" || { echo "FATAL: cannot source common.sh" >&2; exit 5; }

# =============================================================================
# 2. Defaults
# =============================================================================
SCRIPT_VERSION="0.1.0"
PROFILE=""
NFT_FILE=""
SSH_PORT="22"
PERSIST=0
FORCE=0

# =============================================================================
# 3. Functions
# =============================================================================
usage() {
    cat <<'EOF'
Usage: sk-nft-apply [OPTIONS]

Apply a raw nftables ruleset. Generate a safe default-deny ruleset from a
profile, or load your own .nft file. Always syntax-checks (nft -c) first.
Works on Debian/Ubuntu and the RHEL family (auto-detect via common.sh).

PROFILES (built-in inet/filter, default policy drop):
    web-server   loopback + established + SSH + 80/443
    ssh-only     loopback + established + SSH only

SCRIPT FLAGS:
        --profile NAME  Use a built-in profile (web-server | ssh-only)
        --file FILE     Load this .nft ruleset instead of a profile
        --ssh-port N    SSH port for the profile (default 22)
        --persist       After apply, write the ruleset to the family's
                        nftables.conf and enable nftables.service
        --force         Apply even if ufw/firewalld is active (DANGEROUS —
                        the front-end will overwrite on its next reload)

STANDARD FLAGS:
    -h, --help          Show this help and exit
        --version       Print version
    -y, --yes           Non-interactive; requires --profile or --file
    -n, --dry-run       Generate + syntax-check + print the ruleset, do NOT apply
        --log           Tee output to /var/log/linux-skills/
    -v, --verbose       Extra diagnostic output
    -q, --quiet         Errors and final result only

EXIT CODES:
    0  success
    2  usage / flag error
    3  precondition failed (not root, unsupported distro, front-end active)
    4  user aborted
    5  dependency missing (nft)

EXAMPLES:
    sudo sk-nft-apply --profile web-server --dry-run
    sudo sk-nft-apply --profile ssh-only --ssh-port 2222 --persist
    sudo sk-nft-apply --file /etc/nftables/custom.nft --dry-run

WARNING:
    A default-deny ruleset can lock you out of a remote host. Always keep a
    second SSH session open and verify before disconnecting. The profiles
    always accept SSH + established/related to reduce that risk.

AUTHOR:
    Peter Bamuhigire <techguypeter.com> +256784464178
EOF
}

# Emit a built-in profile ruleset to stdout.
generate_profile() {
    local profile="$1" port="$2"
    cat <<EOF
#!/usr/sbin/nft -f
# Generated by sk-nft-apply (profile: ${profile})
flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0 ; policy drop ;
        iif "lo" accept
        ct state established,related accept
        ct state invalid drop
        ip protocol icmp accept
        ip6 nexthdr ipv6-icmp accept
        tcp dport ${port} accept comment "ssh"
EOF
    if [[ "$profile" == "web-server" ]]; then
        printf '        tcp dport { 80, 443 } accept comment "http/https"\n'
    fi
    cat <<'EOF'
        counter comment "default-drop"
    }
    chain forward {
        type filter hook forward priority 0 ; policy drop ;
    }
    chain output {
        type filter hook output priority 0 ; policy accept ;
    }
}
EOF
}

# =============================================================================
# 4. Flag parsing
# =============================================================================
parse_standard_flags "$@"

while [[ ${#REMAINING_ARGS[@]} -gt 0 ]]; do
    case "${REMAINING_ARGS[0]}" in
        --profile)
            PROFILE="${REMAINING_ARGS[1]:-}"
            REMAINING_ARGS=("${REMAINING_ARGS[@]:2}")
            ;;
        --file)
            NFT_FILE="${REMAINING_ARGS[1]:-}"
            REMAINING_ARGS=("${REMAINING_ARGS[@]:2}")
            ;;
        --ssh-port)
            SSH_PORT="${REMAINING_ARGS[1]:-}"
            REMAINING_ARGS=("${REMAINING_ARGS[@]:2}")
            ;;
        --persist)
            PERSIST=1
            REMAINING_ARGS=("${REMAINING_ARGS[@]:1}")
            ;;
        --force)
            FORCE=1
            REMAINING_ARGS=("${REMAINING_ARGS[@]:1}")
            ;;
        *)
            die "unknown argument: ${REMAINING_ARGS[0]} (see --help)" 2
            ;;
    esac
done

# =============================================================================
# 5. Sanity checks
# =============================================================================
require_root
require_family any
require_cmd nft

if [[ -n "$PROFILE" && -n "$NFT_FILE" ]]; then
    die "use either --profile or --file, not both" 2
fi

# In --yes mode the choice must be explicit (no interactive prompt).
if [[ "$YES" == "1" && -z "$PROFILE" && -z "$NFT_FILE" ]]; then
    die "--yes requires --profile or --file" 2
fi

# Interactive: pick a profile if nothing supplied.
if [[ -z "$PROFILE" && -z "$NFT_FILE" ]]; then
    PROFILE=$(select_one "Pick an nftables profile" web-server ssh-only)
fi

if [[ -n "$PROFILE" && "$PROFILE" != "web-server" && "$PROFILE" != "ssh-only" ]]; then
    die "unknown profile: $PROFILE (web-server | ssh-only)" 2
fi
if [[ -n "$NFT_FILE" && ! -f "$NFT_FILE" ]]; then
    die "ruleset file not found: $NFT_FILE" 2
fi

# Front-end guard: raw nft will be overwritten by an active front-end.
FRONTEND=""
if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -qi '^Status: active'; then
    FRONTEND="ufw"
elif systemctl is-active --quiet firewalld 2>/dev/null; then
    FRONTEND="firewalld"
fi
if [[ -n "$FRONTEND" && "$FORCE" != "1" ]]; then
    die "$FRONTEND is active and owns the ruleset; manage rules via it, or pass --force to override" 3
fi
[[ -n "$FRONTEND" && "$FORCE" == "1" ]] && \
    warn "$FRONTEND is active — your raw rules will be lost on its next reload"

# =============================================================================
# 6. Build the candidate ruleset into a temp file
# =============================================================================
RULESET="$(safe_tempfile sk-nft)"
if [[ -n "$NFT_FILE" ]]; then
    cat "$NFT_FILE" > "$RULESET"
    info "using ruleset file: $NFT_FILE"
else
    generate_profile "$PROFILE" "$SSH_PORT" > "$RULESET"
    info "generated profile '$PROFILE' (ssh port $SSH_PORT)"
fi

# Always syntax-check first (does NOT apply).
header "Syntax check (nft -c)"
if run nft -c -f "$RULESET"; then
    pass "ruleset syntax is valid"
else
    die "ruleset failed syntax check — not applying" 1
fi

if [[ "$VERBOSE" == "1" || "$DRY_RUN" == "1" ]]; then
    header "Candidate ruleset"
    cat "$RULESET"
fi

# =============================================================================
# 7. Apply (destructive) — skipped under --dry-run
# =============================================================================
if [[ "$DRY_RUN" == "1" ]]; then
    header "Result"
    pass "dry run: ruleset generated and syntax-checked, NOT applied"
    exit 0
fi

header "Apply ruleset"
warn "this REPLACES the entire live nftables ruleset (flush ruleset)"
if [[ "$YES" == "1" ]]; then
    require_flag PROFILE 2>/dev/null || require_flag NFT_FILE
fi
confirm_destructive "Replace the live nftables ruleset now?" \
    || die "user aborted" 4

backup_dir="/var/log/linux-skills"
backup="${backup_dir}/nft-ruleset-$(date +%Y%m%d-%H%M%S).bak"
mkdir -p "$backup_dir"
nft list ruleset > "$backup" 2>/dev/null || true
info "previous ruleset backed up to $backup"

run nft -f "$RULESET" || die "failed to load ruleset (live ruleset may be partial)" 1
pass "ruleset applied"

# =============================================================================
# 8. Persist (optional)
# =============================================================================
if [[ "$PERSIST" == "1" ]]; then
    header "Persist"
    if [[ "$SK_DISTRO_FAMILY" == "debian" ]]; then
        NFT_CONF="/etc/nftables.conf"
    else
        NFT_CONF="/etc/sysconfig/nftables.conf"
    fi
    [[ -f "$NFT_CONF" ]] && backup_file "$NFT_CONF"
    nft list ruleset | atomic_write "$NFT_CONF"
    info "wrote live ruleset to $NFT_CONF"
    run systemctl enable --now nftables \
        && pass "nftables.service enabled (ruleset survives reboot)" \
        || warn "could not enable nftables.service"
fi

header "Result"
pass "done — verify with: sudo sk-nft-show"
exit 0
